name: "Wiki update"

# When changes to /docs are pushed to main
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Bi-directional Wiki Sync Action
        uses: newrelic/wiki-sync-action@v1.0.1
      